<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>The source code</title>
  <link href="../resources/prettify/prettify.css" type="text/css" rel="stylesheet" />
  <script type="text/javascript" src="../resources/prettify/prettify.js"></script>
  <style type="text/css">
    .highlight { display: block; background-color: #ddd; }
  </style>
  <script type="text/javascript">
    function highlight() {
      document.getElementById(location.hash.replace(/#/, "")).className = "highlight";
    }
  </script>
</head>
<body onload="prettyPrint(); highlight();">
  <pre class="prettyprint lang-js"><span id='java-security-cert-CertPathValidatorException'>/**@class java.security.cert.CertPathValidatorException
</span>@extends java.security.GeneralSecurityException

 An exception indicating one of a variety of problems encountered when
 validating a certification path.
 &lt;p&gt;
 A {@code CertPathValidatorException} provides support for wrapping
 exceptions. The {@link #getCause getCause} method returns the throwable,
 if any, that caused this exception to be thrown.
 &lt;p&gt;
 A {@code CertPathValidatorException} may also include the
 certification path that was being validated when the exception was thrown,
 the index of the certificate in the certification path that caused the
 exception to be thrown, and the reason that caused the failure. Use the
 {@link #getCertPath getCertPath}, {@link #getIndex getIndex}, and
 {@link #getReason getReason} methods to retrieve this information.

 &lt;p&gt;
 &lt;b&gt;Concurrent Access&lt;/b&gt;
 &lt;p&gt;
 Unless otherwise specified, the methods defined in this class are not
 thread-safe. Multiple threads that need to access a single
 object concurrently should synchronize amongst themselves and
 provide the necessary locking. Multiple threads each manipulating
 separate objects need not synchronize.

 @see CertPathValidator

 @since       1.4
 @author      Yassir Elley
*/
var CertPathValidatorException = {

<span id='java-security-cert-CertPathValidatorException-method-getCertPath'>/**Returns the certification path that was being validated when
</span> the exception was thrown.
@return {Object {java.security.cert.CertPath}} the {@code CertPath} that was being validated when
 the exception was thrown (or {@code null} if not specified)
*/
getCertPath : function(  ) {},

<span id='java-security-cert-CertPathValidatorException-method-getIndex'>/**Returns the index of the certificate in the certification path
</span> that caused the exception to be thrown. Note that the list of
 certificates in a {@code CertPath} is zero based. If no
 index has been set, -1 is returned.
@return {Number} the index that has been set, or -1 if none has been set
*/
getIndex : function(  ) {},

<span id='java-security-cert-CertPathValidatorException-method-getReason'>/**Returns the reason that the validation failed. The reason is
</span> associated with the index of the certificate returned by
 {@link #getIndex}.
@return {Object {java.security.cert.CertPathValidatorException.Reason}} the reason that the validation failed, or
    {@code BasicReason.UNSPECIFIED} if a reason has not been
    specified
@since 1.7
*/
getReason : function(  ) {},


};</pre>
</body>
</html>
