Ext.data.JsonP.java_security_cert_CertPathValidatorException_Reason({"tagname":"class","name":"java.security.cert.CertPathValidatorException.Reason","autodetected":{},"files":[{"filename":"Reason.js","href":"Reason.html#java-security-cert-CertPathValidatorException-Reason"}],"since":"1.7","members":[],"alternateClassNames":[],"aliases":{},"id":"class-java.security.cert.CertPathValidatorException.Reason","classIcon":"icon-class","superclasses":[],"subclasses":[],"mixedInto":[],"mixins":[],"parentMixins":[],"requires":[],"uses":[],"html":"<div><pre class=\"hierarchy\"><h4>Files</h4><div class='dependency'><a href='source/Reason.html#java-security-cert-CertPathValidatorException-Reason' target='_blank'>Reason.js</a></div></pre><div class='doc-contents'><p>implements java.io.Serializable</p>\n\n<p> The reason the validation algorithm failed.</p>\n        <p>Available since: <b>1.7</b></p>\n</div><div class='members'></div></div>","meta":{}});