<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>The source code</title>
  <link href="../resources/prettify/prettify.css" type="text/css" rel="stylesheet" />
  <script type="text/javascript" src="../resources/prettify/prettify.js"></script>
  <style type="text/css">
    .highlight { display: block; background-color: #ddd; }
  </style>
  <script type="text/javascript">
    function highlight() {
      document.getElementById(location.hash.replace(/#/, "")).className = "highlight";
    }
  </script>
</head>
<body onload="prettyPrint(); highlight();">
  <pre class="prettyprint lang-js"><span id='jsr166-FutureTaskTest'>/**@class jsr166.FutureTaskTest
</span>@extends jsr166.JSR166TestCase

*/
var FutureTaskTest = {

<span id='jsr166-FutureTaskTest-method-testConstructor'>/**creating a future with a null callable throws NullPointerException
</span>*/
testConstructor : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testConstructor2'>/**creating a future with null runnable throws NullPointerException
</span>*/
testConstructor2 : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testIsDone'>/**isDone is true when a task completes
</span>*/
testIsDone : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testRunAndReset'>/**runAndReset of a non-cancelled task succeeds
</span>*/
testRunAndReset : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testRunAndResetAfterCancel'>/**runAndReset after cancellation fails
</span>*/
testRunAndResetAfterCancel : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testSet'>/**setting value causes get to return it
</span>*/
testSet : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testSetException_get'>/**setException causes get to throw ExecutionException
</span>*/
testSetException_get : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testCancelBeforeRun'>/**cancel(false) before run succeeds
</span>*/
testCancelBeforeRun : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testCancelBeforeRun2'>/**cancel(true) before run succeeds
</span>*/
testCancelBeforeRun2 : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testCancelAfterRun'>/**cancel(false) of a completed task fails
</span>*/
testCancelAfterRun : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testCancelAfterRun2'>/**cancel(true) of a completed task fails
</span>*/
testCancelAfterRun2 : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testCancelInterrupt'>/**cancel(true) interrupts a running task that subsequently succeeds
</span>*/
testCancelInterrupt : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testCancelInterrupt_ThrowsSecurityException'>/**cancel(true) tries to interrupt a running task, but
</span> Thread.interrupt throws (simulating a restrictive security
 manager)
*/
testCancelInterrupt_ThrowsSecurityException : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testCancelInterrupt_taskFails'>/**cancel(true) interrupts a running task that subsequently throws
</span>*/
testCancelInterrupt_taskFails : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testCancelNoInterrupt'>/**cancel(false) does not interrupt a running task
</span>*/
testCancelNoInterrupt : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testGetRun'>/**run in one thread causes get in another thread to retrieve value
</span>*/
testGetRun : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testGetSet'>/**set in one thread causes get in another thread to retrieve value
</span>*/
testGetSet : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testTimedGet_Cancellation'>/**Cancelling a task causes timed get in another thread to throw
</span> CancellationException
*/
testTimedGet_Cancellation : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testTimedGet_Cancellation_interrupt'>/**
</span>*/
testTimedGet_Cancellation_interrupt : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testTimedGet_Cancellation'>/**
</span>*/
testTimedGet_Cancellation : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testGet_ExecutionException'>/**A runtime exception in task causes get to throw ExecutionException
</span>*/
testGet_ExecutionException : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testTimedGet_ExecutionException2'>/**A runtime exception in task causes timed get to throw ExecutionException
</span>*/
testTimedGet_ExecutionException2 : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testGet_interruptible'>/**get is interruptible
</span>*/
testGet_interruptible : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testTimedGet_interruptible'>/**timed get is interruptible
</span>*/
testTimedGet_interruptible : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testGet_TimeoutException'>/**A timed out timed get throws TimeoutException
</span>*/
testGet_TimeoutException : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testGet_NullTimeUnit'>/**timed get with null TimeUnit throws NullPointerException
</span>*/
testGet_NullTimeUnit : function(  ) {},

<span id='jsr166-FutureTaskTest-method-testGet_NegativeInfinityTimeout'>/**timed get with most negative timeout works correctly (i.e. no
</span> underflow bug)
*/
testGet_NegativeInfinityTimeout : function(  ) {},


};</pre>
</body>
</html>
