<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>The source code</title>
  <link href="../resources/prettify/prettify.css" type="text/css" rel="stylesheet" />
  <script type="text/javascript" src="../resources/prettify/prettify.js"></script>
  <style type="text/css">
    .highlight { display: block; background-color: #ddd; }
  </style>
  <script type="text/javascript">
    function highlight() {
      document.getElementById(location.hash.replace(/#/, "")).className = "highlight";
    }
  </script>
</head>
<body onload="prettyPrint(); highlight();">
  <pre class="prettyprint lang-js"><span id='java-lang-reflect-InvocationTargetException'>/**@class java.lang.reflect.InvocationTargetException
</span>@extends java.lang.ReflectiveOperationException

 InvocationTargetException is a checked exception that wraps
 an exception thrown by an invoked method or constructor.

 &lt;p&gt;As of release 1.4, this exception has been retrofitted to conform to
 the general purpose exception-chaining mechanism.  The &quot;target exception&quot;
 that is provided at construction time and accessed via the
 {@link #getTargetException}() method is now known as the &lt;i&gt;cause&lt;/i&gt;,
 and may be accessed via the {@link Throwable#getCause()} method,
 as well as the aforementioned &quot;legacy method.&quot;

 @see Method
 @see Constructor
*/
var InvocationTargetException = {

<span id='java-lang-reflect-InvocationTargetException-method-getTargetException'>/**Get the thrown target exception.
</span>
 &lt;p&gt;This method predates the general-purpose exception chaining facility.
 The {@link Throwable#getCause()} method is now the preferred means of
 obtaining this information.
@return {Object {java.lang.Throwable}} the thrown target exception (cause of this exception).
*/
getTargetException : function(  ) {},

<span id='java-lang-reflect-InvocationTargetException-method-getCause'>/**Returns the cause of this exception (the thrown target exception,
</span> which may be {@code null}).
@return {Object {java.lang.Throwable}} the cause of this exception.
@since 1.4
*/
getCause : function(  ) {},


};</pre>
</body>
</html>
