<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>The source code</title>
  <link href="../resources/prettify/prettify.css" type="text/css" rel="stylesheet" />
  <script type="text/javascript" src="../resources/prettify/prettify.js"></script>
  <style type="text/css">
    .highlight { display: block; background-color: #ddd; }
  </style>
  <script type="text/javascript">
    function highlight() {
      document.getElementById(location.hash.replace(/#/, "")).className = "highlight";
    }
  </script>
</head>
<body onload="prettyPrint(); highlight();">
  <pre class="prettyprint lang-js"><span id='junit-framework-TestResult'>/**@class junit.framework.TestResult
</span>@extends java.lang.Object

 A &lt;code&gt;TestResult&lt;/code&gt; collects the results of executing
 a test case. It is an instance of the Collecting Parameter pattern.
 The test framework distinguishes between &lt;i&gt;failures&lt;/i&gt; and &lt;i&gt;errors&lt;/i&gt;.
 A failure is anticipated and checked for with assertions. Errors are
 unanticipated problems like an {@link ArrayIndexOutOfBoundsException}.

 @see Test
*/
var TestResult = {

<span id='junit-framework-TestResult-method-addError'>/**Adds an error to the list of errors. The passed in exception
</span> caused the error.
*/
addError : function(  ) {},

<span id='junit-framework-TestResult-method-addFailure'>/**Adds a failure to the list of failures. The passed in exception
</span> caused the failure.
*/
addFailure : function(  ) {},

<span id='junit-framework-TestResult-method-addListener'>/**Registers a TestListener
</span>*/
addListener : function(  ) {},

<span id='junit-framework-TestResult-method-removeListener'>/**Unregisters a TestListener
</span>*/
removeListener : function(  ) {},

<span id='junit-framework-TestResult-method-endTest'>/**Informs the result that a test was completed.
</span>*/
endTest : function(  ) {},

<span id='junit-framework-TestResult-method-errorCount'>/**Gets the number of detected errors.
</span>*/
errorCount : function(  ) {},

<span id='junit-framework-TestResult-method-errors'>/**Returns an Enumeration for the errors
</span>*/
errors : function(  ) {},

<span id='junit-framework-TestResult-method-failureCount'>/**Gets the number of detected failures.
</span>*/
failureCount : function(  ) {},

<span id='junit-framework-TestResult-method-failures'>/**Returns an Enumeration for the failures
</span>*/
failures : function(  ) {},

<span id='junit-framework-TestResult-method-runCount'>/**Gets the number of run tests.
</span>*/
runCount : function(  ) {},

<span id='junit-framework-TestResult-method-runProtected'>/**Runs a TestCase.
</span>*/
runProtected : function(  ) {},

<span id='junit-framework-TestResult-method-shouldStop'>/**Checks whether the test run should stop
</span>*/
shouldStop : function(  ) {},

<span id='junit-framework-TestResult-method-startTest'>/**Informs the result that a test will be started.
</span>*/
startTest : function(  ) {},

<span id='junit-framework-TestResult-method-stop'>/**Marks that the test run should stop.
</span>*/
stop : function(  ) {},

<span id='junit-framework-TestResult-method-wasSuccessful'>/**Returns whether the entire test was successful or not.
</span>*/
wasSuccessful : function(  ) {},


};</pre>
</body>
</html>
